# Generated by Django 4.0.5 on 2022-06-10 07:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=2000)),
                ("major_project_sorce_code", models.URLField(blank=True, null=True)),
                ("minor_project_sorce_code", models.URLField(blank=True, null=True)),
                ("major_project_presentation", models.URLField(blank=True, null=True)),
                ("minor_project_presentation", models.URLField(blank=True, null=True)),
                ("major_project_report", models.URLField(blank=True, null=True)),
                ("minor_project_report", models.URLField(blank=True, null=True)),
                (
                    "is_approved",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("date_posted", models.DateField(auto_now_add=True, null=True)),
                ("date_approved", models.DateField(blank=True, null=True)),
                ("last_modified", models.DateField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="student.student",
                    ),
                ),
            ],
        ),
    ]
