# Generated by Django 4.0.5 on 2022-06-11 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_rename_registation_number_student_registration_number"),
        ("project", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student.student"
            ),
        ),
    ]
