# Generated by Django 4.0.5 on 2022-06-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "registation_number",
                    models.CharField(
                        max_length=11, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=125)),
                ("last_name", models.CharField(max_length=125)),
            ],
        ),
    ]
