# Generated by Django 4.0.5 on 2022-06-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="registation_number",
            new_name="registration_number",
        ),
    ]
